# Include tasks from other gems included in your Gemfile
require 'capistrano/sunzistrano'

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
